export const EDIT_FEATURE = 'EDIT_FEATURE';
export const ADD_FEATURE = 'ADD_FEATURE';
export const REMOVE_FEATURE = 'REMOVE_FEATURE';
export const THUMB_UP_FEATURE = 'THUMB_UP_FEATURE';
export const THUMB_DOWN_FEATURE = 'THUMB_DOWN_FEATURE';

export default {
    EDIT_FEATURE, ADD_FEATURE, REMOVE_FEATURE, THUMB_UP_FEATURE, THUMB_DOWN_FEATURE
}